version: '2'
services:
  miniflux:
    image: miniflux/miniflux:2.0.0
    ports:
      - "80:8080"
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
